// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Prontuario.Infrastructure.Persistence;

#nullable disable

namespace Prontuario.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260920214617_ExportacaoConectorEChaveIntegracao")]
    partial class ExportacaoConectorEChaveIntegracao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Prontuario.Domain.Entities.Atendimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConsentimentoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ConsentimentoGravacao")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErroProcessamentoIA")
                        .HasColumnType("text");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PacienteRefId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteRefId");

                    b.ToTable("Atendimentos");
                });

            modelBuilder.Entity("Prontuario.Domain.Entities.Clinica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ChaveIntegracaoCriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChaveIntegracaoHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ChaveIntegracaoPrefixo")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModoOperacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("WebhookSecretProtegido")
                        .HasColumnType("text");

                    b.Property<string>("WebhookUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ChaveIntegracaoHash");

                    b.ToTable("Clinicas");
                });

            modelBuilder.Entity("Prontuario.Domain.Entities.ConfiguracaoIA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AtualizadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChaveApiProtegida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChaveApiSufixo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModeloTexto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ModeloTranscricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId")
                        .IsUnique();

                    b.ToTable("ConfiguracoesIA");
                });

            modelBuilder.Entity("Prontuario.Domain.Entities.GravacaoAudio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AtendimentoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DuracaoSegundos")
                        .HasColumnType("integer");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId")
                        .IsUnique();

                    b.ToTable("GravacoesAudio");
                });

            modelBuilder.Entity("Prontuario.Domain.Entities.LogAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("AtendimentoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LogsAuditoria");
                });

            modelBuilder.Entity("Prontuario.Domain.Entities.NotaExportavel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AtendimentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConteudoFormatado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destino")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ExportadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevisadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TentativasExportacao")
                        .HasColumnType("integer");

                    b.Property<string>("UltimoErroExportacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId")
                        .IsUnique();

                    b.ToTable("NotasExportaveis");
                });

            modelBuilder.Entity("Prontuario.Domain.Entities.PacienteRef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Contato")
                        .HasColumnType("text");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("HistoricoClinicoResumido")
                        .HasColumnType("text");

                    b.Property<string>("IdExternoEmr")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Prontuario.Domain.Entities.ProntuarioRegistro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Antecedentes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AssinadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssinadoPorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AtendimentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Cid10")
                        .HasColumnType("text");

                    b.Property<string>("Conduta")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExameFisico")
                        .HasColumnType("text");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("boolean");

                    b.Property<string>("Hda")
                        .HasColumnType("text");

                    b.Property<string>("HipoteseDiagnostica")
                        .HasColumnType("text");

                    b.Property<string>("QueixaPrincipal")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId")
                        .IsUnique();

                    b.ToTable("Prontuarios");
                });

            modelBuilder.Entity("Prontuario.Domain.Entities.RascunhoIA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Antecedentes")
                        .HasColumnType("text");

                    b.Property<string>("Cid10Sugerido")
                        .HasColumnType("text");

                    b.Property<string>("Conduta")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExameFisico")
                        .HasColumnType("text");

                    b.Property<string>("Hda")
                        .HasColumnType("text");

                    b.Property<string>("HipoteseDiagnostica")
                        .HasColumnType("text");

                    b.Property<string>("QueixaPrincipal")
                        .HasColumnType("text");

                    b.Property<Guid>("TranscricaoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TranscricaoId")
                        .IsUnique();

                    b.ToTable("RascunhosIA");
                });

            modelBuilder.Entity("Prontuario.Domain.Entities.Transcricao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GravacaoAudioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GravacaoAudioId")
                        .IsUnique();

                    b.ToTable("Transcricoes");
                });

            modelBuilder.Entity("Prontuario.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Prontuario.Domain.Entities.Atendimento", b =>
                {
                    b.HasOne("Prontuario.Domain.Entities.Usuario", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Prontuario.Domain.Entities.PacienteRef", "PacienteRef")
                        .WithMany("Atendimentos")
                        .HasForeignKey("PacienteRefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("PacienteRef");
                });

            modelBuilder.Entity("Prontuario.Domain.Entities.ConfiguracaoIA", b =>
                {
                    b.HasOne("Prontuario.Domain.Entities.Clinica", "Clinica")
                        .WithMany()
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("Prontuario.Domain.Entities.GravacaoAudio", b =>
                {
                    b.HasOne("Prontuario.Domain.Entities.Atendimento", "Atendimento")
                        .WithOne("GravacaoAudio")
                        .HasForeignKey("Prontuario.Domain.Entities.GravacaoAudio", "AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atendimento");
                });

            modelBuilder.Entity("Prontuario.Domain.Entities.LogAuditoria", b =>
                {
                    b.HasOne("Prontuario.Domain.Entities.Atendimento", "Atendimento")
                        .WithMany("LogsAuditoria")
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Prontuario.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atendimento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Prontuario.Domain.Entities.NotaExportavel", b =>
                {
                    b.HasOne("Prontuario.Domain.Entities.Atendimento", "Atendimento")
                        .WithOne("NotaExportavel")
                        .HasForeignKey("Prontuario.Domain.Entities.NotaExportavel", "AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atendimento");
                });

            modelBuilder.Entity("Prontuario.Domain.Entities.PacienteRef", b =>
                {
                    b.HasOne("Prontuario.Domain.Entities.Clinica", "Clinica")
                        .WithMany("Pacientes")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("Prontuario.Domain.Entities.ProntuarioRegistro", b =>
                {
                    b.HasOne("Prontuario.Domain.Entities.Atendimento", "Atendimento")
                        .WithOne("Prontuario")
                        .HasForeignKey("Prontuario.Domain.Entities.ProntuarioRegistro", "AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atendimento");
                });

            modelBuilder.Entity("Prontuario.Domain.Entities.RascunhoIA", b =>
                {
                    b.HasOne("Prontuario.Domain.Entities.Transcricao", "Transcricao")
                        .WithOne("RascunhoIA")
                        .HasForeignKey("Prontuario.Domain.Entities.RascunhoIA", "TranscricaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transcricao");
                });

            modelBuilder.Entity("Prontuario.Domain.Entities.Transcricao", b =>
                {
                    b.HasOne("Prontuario.Domain.Entities.GravacaoAudio", "GravacaoAudio")
                        .WithOne("Transcricao")
                        .HasForeignKey("Prontuario.Domain.Entities.Transcricao", "GravacaoAudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GravacaoAudio");
                });

            modelBuilder.Entity("Prontuario.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Prontuario.Domain.Entities.Clinica", "Clinica")
                        .WithMany("Usuarios")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("Prontuario.Domain.Entities.Atendimento", b =>
                {
                    b.Navigation("GravacaoAudio");

                    b.Navigation("LogsAuditoria");

                    b.Navigation("NotaExportavel");

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("Prontuario.Domain.Entities.Clinica", b =>
                {
                    b.Navigation("Pacientes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Prontuario.Domain.Entities.GravacaoAudio", b =>
                {
                    b.Navigation("Transcricao");
                });

            modelBuilder.Entity("Prontuario.Domain.Entities.PacienteRef", b =>
                {
                    b.Navigation("Atendimentos");
                });

            modelBuilder.Entity("Prontuario.Domain.Entities.Transcricao", b =>
                {
                    b.Navigation("RascunhoIA");
                });
#pragma warning restore 612, 618
        }
    }
}
